### ISSUE TITLE
Alertmanager2Es responding 404 page not found to AlertManager

### ISSUE THREAD

**Issue by ewlilmsa** [webdevops/alertmanager2es#2]
Hi, dear experts

I've started the alertmanager2es in a VM where is receiving the alerts from Alertmanager, in an older release I was able to capture the alert in the plugin  alertmanager2es, but I was unable to see the alertmanager2es triggering any request to send it to elasticsearch, I couldn't figure it out why, so I've moved to this new version, but for the same event now I'm getting 404 page not found as a response from alermanager2es to alertmanager. How can I address this issue? Ideas, feedback is welcome.

Regards,

**Comment by mblaschke** [comment]
how does your alertmanager config look like for alertmanager2es?
have you deployed it via docker/container? is the endpoint `/webhook` reachable? can you reach `/healthz` and `/metrics`?

**Comment by ewlilmsa** [comment]
Hi Markus, 
Thanks for the quick response.
my alertmanager config looks like this:
apiVersion: v1
data:
  alertmanager.yml: |-
    receivers
    - name: prometheus-webhook-am2es
      webhook_configs:
        - url: 'http://10.10.50.104:9097'
          send_resolved: true
    route:
      group_by: ['...']
      group_wait: 10s
      group_interval: 5m
      receiver: prometheus-webhook-am2es
      repeat_interval: 4h
      routes:
        - receiver: prometheus-webhook-am2es
          continue: true

deployed as endpoint /webhook, and it is reachable.

If I use the old alertmanger2es version then I get:
ubuntu@vm004:~$ curl 10.10.50.104:9097
alertmanager2es unknown (go1.12.8)ubuntu@vm004:~$

but if I use this one, then I get:

ubuntu@vm004:~$ curl 10.10.50.104:9097
404 page not found

Regards

**Comment by ewlilmsa** [comment]
And if I stop the alermanager2es then I see:
curl: (7) Failed to connect to 10.10.50.104 port 9097: Connection refused
Which is an expected response

**Comment by mblaschke** [comment]
have you tried with `http://10.10.50.104:9097/webhook`? (see example in README.md)

eg:
```
apiVersion: v1
data:
  alertmanager.yml: |-
    receivers
    - name: prometheus-webhook-am2es
      webhook_configs:
        - url: 'http://10.10.50.104:9097/webhook'
          send_resolved: true
    route:
      group_by: ['...']
      group_wait: 10s
      group_interval: 5m
      receiver: prometheus-webhook-am2es
      repeat_interval: 4h
      routes:
        - receiver: prometheus-webhook-am2es
          continue: true
```
